/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProblemSolvingJava;
import LibraryManagementSystem.LibraryManagement;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryManagementTest {
    @Test void appHasAGreeting() {
        LibraryManagement classUnderTest = new LibraryManagement();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
