/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 */
package LibraryManagementSystem;

import LibraryManagementSystem.enums.Genre;

public class LibraryManagement {

    public static void main(String[] args) {
        // Creating objects (instances) of the Book class
        /*Book book1 = new Book(
                "The Great Gatsby",
                "F. Scott Fitzgerald",
                "1234567890");

        Book book2 = new Book(
                "1984",
                "George Orwell",
                "0987654321");*/

        PhysicalBook physicalBook = new PhysicalBook(
                "The Great Gatsby",
                "F. Scott Fitzgerald",
                "1234567890",
                Genre.FICTION,
                180);

        PhysicalBook physicalBook2 = new PhysicalBook(
                "1984",
                "George Orwell",
                "0987654321",
                Genre.BIOGRAPHY,
                200);

        EBook eBook = new EBook(
                "Database System Concepts",
                "Shymor",
                "0987654321",
                Genre.COMPUTER_SCIENCE,
                "https://www.micgrawhall.com");

        // Using methods on objects
        physicalBook.displayBookInfo();
        physicalBook.borrow();
        physicalBook.borrow();  // Try borrowing the same book again
        physicalBook.returnBook();

        System.out.println();

        physicalBook2.displayBookInfo();
        physicalBook2.borrow();
        physicalBook2.returnBook();

        System.out.println();
        eBook.displayBookInfo();
        eBook.borrow();
        eBook.returnBook();

        // Members operations
        Library libraryOP = new Library();
        libraryOP.addMember("M001","Alice");
        libraryOP.addMember("M002","Bob");

        Member alice = libraryOP.findMemberById("M001");
        if (alice!=null) {
            alice.borrowBook(physicalBook);
            alice.borrowBook(eBook);
            alice.listBorrowedBooks();
            alice.returnBook(physicalBook);
            alice.listBorrowedBooks();
        }

        Member bob = libraryOP.findMemberById("M002");
        if (bob!=null) {
            bob.borrowBook(physicalBook);
            bob.listBorrowedBooks();
            bob.returnBook(physicalBook);
            bob.listBorrowedBooks();
        }

    }
}
