/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 */
package LibraryManagementSystem;

public class LibraryManagement {

    public static void main(String[] args) {
        // Creating objects (instances) of the Book class
        Book book1 = new Book(
                "The Great Gatsby",
                "F. Scott Fitzgerald",
                "1234567890");

        Book book2 = new Book(
                "1984",
                "George Orwell",
                "0987654321");

        EBook eBook = new EBook(
                "Database System Concepts",
                "Shymor",
                "0987654321",
                "https://www.micgrawhall.com");

        // Using methods on objects
        book1.displayBookInfo();
        book1.borrow();
        book1.borrow();  // Try borrowing the same book again
        book1.returnBook();

        System.out.println(); // Just a line break

        book2.displayBookInfo();
        book2.borrow();
        book2.returnBook();

        System.out.println();
        eBook.displayBookInfo();
        eBook.borrow();
        eBook.borrow();

    }
}
