/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VaccineCount;

import VaccineCount.Utils.Constants;
import VaccineCount.Utils.Utils;
import VaccineCount.models.OutputInfoModel;

public class App {
        
    public static void main(String[] args) {               
        InputFromUser userInput = new InputFromUser();

        int numberOfCandidates = userInput.inputNumberOfCandidates();
        int numberOfVaccines = userInput.inputNumberOfVaccine();
        
        if(numberOfVaccines>numberOfCandidates){
            System.out.println(Constants.INVALID_CANDIDATE);
            return;
        }
        
        int vaccineLimitAgeGroup = userInput.inputVaccineLimit();
        
        OutputInfoModel infoInstance = OutputInfoModel.getInstance();
        infoInstance.setTotalVaccine(numberOfVaccines);
        infoInstance.setVaccineAgeLimit(vaccineLimitAgeGroup);
        
        Utils operation = new Utils(infoInstance);
        operation.organizedMenWomenCadidate(numberOfCandidates);
        operation.devideTotalVaccineEqually(numberOfVaccines);
        
        operation.doOperationForMen();
        operation.doOperationForWomen();
        
        UserOutput userOutput = new UserOutput(infoInstance);
        userOutput.showResult();
        
    }
    
    
    
}
